// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROJETO_LOGIN.Context;

#nullable disable

namespace PROJETO_LOGIN.Migrations
{
    [DbContext(typeof(QuizContext))]
    [Migration("20240926120430_AtualizarTabelaResultado")]
    partial class AtualizarTabelaResultado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PROJETO_LOGIN.Entities.Resultado", b =>
                {
                    b.Property<string>("Relatorio_Perfil")
                        .HasColumnType("longtext");

                    b.Property<string>("Resultado_Teste")
                        .HasColumnType("longtext");

                    b.Property<int>("Tabela_Resposta_Teste")
                        .HasColumnType("int");

                    b.Property<int>("Tabela_Tipo_Pergunta")
                        .HasColumnType("int");

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("PROJETO_LOGIN.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
